spring.application.name=notification-service
server.port=8888

#email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=daniel18.derick@gmail.com
spring.mail.password=tbhu okar atye wleq
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
#https://myaccount.google.com/apppasswords


eureka:
instance:
prefer-ip-address: true
client:
fetch-registry: true
register-with-eureka: true
service-url:
defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}